### ISSUE TITLE
No version set for command ... - still happening in v0.7.1

### ISSUE THREAD

**Issue by eksperimental** [asdf-vm/asdf#517]
Still having the "no version set" issue (originally reported in https://github.com/asdf-vm/asdf/issues/488) with v0.7.1 even after run `asdf reshim`

### Steps to reproduce

my .tool-versions is

```
erlang 21.0.6
elixir path:/home/eksperimental/elixir/
```

```
$ cd /home/eksperimental/elixir/
$ iex
asdf: No version set for command iex
you might want to add one of the following in your .tool-versions file:

elixir 1.4.4
elixir 1.7.4
elixir 1.8.0
elixir 1.8.1
```

### Expected behavior

to run `/home/eksperimental/elixir/bin/iex`

### Actual behavior

```
asdf: No version set for command iex
```

### Environment

**OS**: Ubuntu GNU/Linux 16.04 32 bits

**asdf version**: v0.7.1

**Comment by Stratus3D** [comment]
I tested on my machine and got the same behavior. Tests are passing, so it seems like we are either not testing this feature at all, or we are testing it incorrectly and getting false positives.

**Comment by nextl00p** [comment]
```
$ erl
asdf: No version set for command erl
you might want to add one of the following in your .tool-versions file:

erlang 19.0
erlang 19.3.6
erlang 20.2
erlang 21.0-rc1
$ asdf list erlang
  19.0
  19.3.6
  20.2
  21.0-rc1
  21.0
$ cat .tool-versions 
erlang 21.0
$ asdf local erlang 21.0-rc1
$ erl
Erlang/OTP 21 [RELEASE CANDIDATE 1] [erts-10.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Eshell V10.0  (abort with ^G)
1> 

```

Very strange. I am installing various Erlang versions on the same machine. So far only Erlang 21.0 is failing. I am on Ubuntu. Tried to reproduce on macOS by installing Erlang 21.0 as well, but there it's working fine.

**Comment by Stratus3D** [comment]
@nextl00p the reason you are getting that message is because your `.tool-versions` file specifies a version (`21.0`) that is not installed (You've got `21.0-rc1` installed, but that's not the same version). The behavior is correct, but the error message you are seeing is not helpful. It should say ```
No installed version set for command erl
You may want to install version 21.0, or you may want to change to one of the following in your .tool-versions file:
...
```

**Comment by nextl00p** [comment]
@Stratus3D why is 21.0 listed in `asdf list erlang`?

**Comment by rob-brown** [comment]
I updated from v0.5.1 to v0.7.1 today on macOS. Now I'm seeing this issue:

```
asdf: No version set for command erl
you might want to add one of the following in your .tool-versions file:

erlang 19.3
erlang 20.0
erlang 20.1
erlang 21.1
erlang 21.2.3
```

I had a similar issue today with a Linux computer. I fixed it by uninstalling all the versions and reinstalling them. I did that on macOS. Unfortunately, it's no longer able to install Erlang. 

```
Building Erlang/OTP 21.2.3 (asdf_21.2.3), please wait...
APPLICATIONS DISABLED (See: /Users/robert/.asdf/plugins/erlang/kerl-home/builds/asdf_21.2.3/otp_build_21.2.3.log)
 * crypto         : No usable OpenSSL found
 * odbc           : ODBC library - header check failed
 * ssh            : No usable OpenSSL found
 * ssl            : No usable OpenSSL found

DOCUMENTATION INFORMATION (See: /Users/robert/.asdf/plugins/erlang/kerl-home/builds/asdf_21.2.3/otp_build_21.2.3.log)
 * documentation  : 
 *                  fop is missing.
 *                  Using fakefop to generate placeholder PDF files.

Build failed.
      _driver_dl_open in io.o
      _driver_dl_sym in io.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [/Users/robert/.asdf/plugins/erlang/kerl-home/builds/asdf_21.2.3/otp_src_21.2.3/bin/x86_64-apple-darwin18.5.0/beam.prof.smp] Error 1
make[3]: *** [opt] Error 2
make[2]: *** [opt] Error 2
make[1]: *** [smp] Error 2
make: *** [emulator_profile_generate] Error 2

Please see /Users/robert/.asdf/plugins/erlang/kerl-home/builds/asdf_21.2.3/otp_build_21.2.3.log for full details.
```

Here's the log:

[otp_build_21.2.3.log](https://github.com/asdf-vm/asdf/files/3188979/otp_build_21.2.3.log)

**Comment by rob-brown** [comment]
I downgraded to v0.5.1. I'm still unable to install Erlang. I also tried this to fix the OpenSSL issues:

```
env ERLANG_OPENSSL_PATH=/usr/local asdf install
```

That's worked in the past but I still get the same results. This bug is so bad I'm forced to remove `asdf` for now.

**Comment by paulswartz** [comment]
It looks like an issue with how the shims handle versions which are a prefix of another installed version. I should have a patch shortly.

**Comment by eksperimental** [comment]
> I downgraded to v0.5.1. I'm still unable to install Erlang. I also tried this to fix the OpenSSL issues:
> 
> ```
> env ERLANG_OPENSSL_PATH=/usr/local asdf install
> ```
> 
> That's worked in the past but I still get the same results. This bug is so bad I'm forced to remove `asdf` for now.

I managed to make it work with v0.6.3

**Comment by eksperimental** [comment]
Sorry, but I tried it with v0.7.2 and master and the problem is still there. So I think the issue should be reopened

**Comment by niccolox** [comment]
I am on ubuntu 19.04, fresh install of v0.7.2 and am seeing the same issue with erlang and elixir

**Comment by paulswartz** [comment]
What versions of Elixir/Erlang do you have installed? `asdf list elixir` and `asdf list erlang`

**Comment by eksperimental** [comment]
@paulswartz 
```
$ asdf list elixir;
  1.8.2
  1.9.0

$ asdf list erlang
  21.3.8.1
  22.0

```

**Comment by paulswartz** [comment]
By any change is your `.tool-versions` file in the root directory? If not, can you share that as well?

**Comment by eksperimental** [comment]
yes, .tool-versions was updated accordingly

```
#erlang 21.3.8.1
erlang 22.0
elixir path:/home/eksperimental/elixir/
```

**Comment by wojtekmach** [comment]
I'm getting the same error:

```
~% asdf version
version: v0.7.2
```

```
~% cat ~/.tool-versions
erlang 22.0.4
elixir path:/Users/wojtek/src/elixir
```

```
~% asdf list elixir
  1.9.0-otp-22
```

```
~% iex
asdf: No version set for command iex
you might want to add one of the following in your .tool-versions file:

elixir 1.9.0-otp-22
```

This is likely a separate issue, but mentioning just in case that this doesn't work either:

```
~% asdf global elixir path:/Users/wojtek/src/elixir
sed: 1: "s/^elixir .*$/elixir pa ...": bad flag in substitute command: 'U'
rm: /Users/wojtek/src/dotfiles/asdf/.tool-versions.bak: No such file or directory
```

**Comment by wojtekmach** [comment]
For posterity, as a workaround instead of using `asdf global elixir path:/Users/wojtek/src/elixir` I used the following trick (thanks @ericmj for the tip!):

```
$ ln -s ~/src/elixir ~/.asdf/installs/elixir/git
$ asdf global elixir git
```

btw, given the original error still happens on 0.7.2, perhaps worth reopening the issue.

**Comment by Stratus3D** [comment]
@wojtekmach can you open up another issue for that `asdf global elixir path` bug?

**Comment by wojtekmach** [comment]
@Stratus3D good call, I created https://github.com/asdf-vm/asdf/issues/559.

**Comment by eksperimental** [comment]
Still this one needs to be reopened as it hasn't been fixed yet

**Comment by aislanmaia** [comment]
Happening to me when `npx nodemon` 
I've installed nodejs version `13.2.0`
Issue: 
```
asdf: No version set for command nodemon
you might want to add one of the following in your .tool-versions file:

nodejs 13.1.0
```
asdf version is `0.7.5`

My `.tool-versions`:
```
nodejs 13.2.0
elixir 1.8.1-otp-21
erlang 21.0.4
postgres 10.5
elm 0.19.1
```

**Comment by LDonoughe** [comment]
I believe I'm getting the same error with npx:
```
$ cat .tool-versions
nodejs 10.17.0
$ npx react-native init ReactNativeApp
asdf: No version set for command react-native
you might want to add one of the following in your .tool-versions file:

nodejs 10.7.0
$ asdf --version
v0.7.6-6207e42
```

**Comment by Stratus3D** [comment]
@aislanmaia @LDonoughe is this related to your issue - https://github.com/asdf-vm/asdf-nodejs/issues/141?

**Comment by LDonoughe** [comment]
@Stratus3D Looks similar, I'll comment on that issue

**Comment by jaydorsey** [comment]
I'm seeing similar behavior here, after upgrading a ruby version in a repository. 	`bundle exec` commands no longer work, pointing to the previous version of ruby even though I've reshimmed and tried a number of other potential fixes (previous commits/versions, restarting terminal, etc.)
